### ISSUE TITLE
如何使用环境变量嵌套

### ISSUE THREAD

**Issue by spursy** [devsapp/fc#1000]
- 获取全局变量：${vars.*}
- 获取当前机器中的环境变量：${env(环境变量)}

**如下：**
```
vars: #公共全局变量
  region: cn-hongkong
  service:
     test: "test-role"
     prod: "prod-role"
```

机器中的环境变量是 test 或 prod，我如何根据机器中的环境变量获取全局环境变量中对应的 role？

**Comment by zxypro1** [comment]
vars暂不支持嵌套写法。可以尝试改一下yaml写法：
```
vars: #公共全局变量
  region: cn-hongkong
  service:
     role: ${env('XXX')}-role

...
  role: ${vars.service.role}
```
