### ISSUE TITLE
使用 fun2fc 转化 sls 日志工程时 logstore 缺漏

### ISSUE THREAD

**Issue by whaohan** [devsapp/fc#125]
在**将基于 fun 工具的函数计算工程转化为基于 s 工具**时，我们需要使用命令 `s cli fc-transform fun2fc` 进行配置文件的转化。

这是一个非常好用的工具，能够方便快捷地将 fun 的配置文件转化为 s 的配置文件。但是，在使用的过程中，我发现了这个工具的一个小问题。在我的 fun 配置中，sls 项目由**两个** logstore 组成，使用 `fun2fc` 工具转化之后，却只剩下**一个** logstore。

附转化前后部分配置（转化前有function-logs与access-logs，转化后只剩下access-logs）：

```
log-simple-transcode:
  Type: 'Aliyun::Serverless::Log'
  Properties:
    Description: The log of all the functions of video transcoder app
  function-logs:
    Type: 'Aliyun::Serverless::Log::Logstore'
    Properties:
      TTL: 10
      ShardCount: 2
  access-logs:
    Type: 'Aliyun::Serverless::Log::Logstore'
    Properties:
      TTL: 10
      ShardCount: 2
```
```
log-simple-transcode:
  component: devsapp/sls
  props:
    regionId: ${vars.region}
    project: log-simple-transcode
    description: The log of all the functions of video transcoder app
    logstore: access-logs
    logstoreOption:
      ttl: 10
      shardCount: 2
```

**Comment by whaohan** [comment]
经[文档查阅](https://github.com/devsapp/sls)，我发现 logstore 属性不支持数组格式，目前我采用两个将其拆分为两个日志项目来解决这个问题，下面是我的 s 配置：

```
log-simple-transcode1:
  component: devsapp/sls
  props:
    regionId: ${vars.region}
    project: log-simple-transcode
    description: The log of all the functions of video transcoder app
    logstore: access-logs
    logstoreOption:
      ttl: 10
      shardCount: 2

log-simple-transcode2:
  component: devsapp/sls
  props:
    regionId: ${vars.region}
    project: log-simple-transcode
    description: The log of all the functions of video transcoder app
    logstore: function-logs
    logstoreOption:
      ttl: 10
      shardCount: 2 
```

如果有更简洁的配置方式，希望您能在这个 issue 中告诉我。

**Comment by anycodes** [comment]
如果非要说简洁模式，可能只是通过vars来做一些全局设置，但是实际上也没有简洁多少。这个可以考虑在未来支持数组形式。

@wss-git 请shoushuai这里帮忙看一下。

**Comment by wss-git** [comment]
> 经[文档查阅](https://github.com/devsapp/sls)，我发现 logstore 属性不支持数组格式，目前我采用两个将其拆分为两个日志项目来解决这个问题，下面是我的 s 配置：
> 
> ```
> log-simple-transcode1:
>   component: devsapp/sls
>   props:
>     regionId: ${vars.region}
>     project: log-simple-transcode
>     description: The log of all the functions of video transcoder app
>     logstore: access-logs
>     logstoreOption:
>       ttl: 10
>       shardCount: 2
> 
> log-simple-transcode2:
>   component: devsapp/sls
>   props:
>     regionId: ${vars.region}
>     project: log-simple-transcode
>     description: The log of all the functions of video transcoder app
>     logstore: function-logs
>     logstoreOption:
>       ttl: 10
>       shardCount: 2 
> ```
> 
> 如果有更简洁的配置方式，希望您能在这个 issue 中告诉我。

经过考虑这块可以修改一下，之前的格式也支持，然后也支持另一种格式
`````
log-simple-transcode1:
  component: devsapp/sls
  props:
    regionId: ${vars.region}
    project: log-simple-transcode
    description: The log of all the functions of video transcoder app
    logstore: 
      - name: access-logs
        option:
          ttl: 10
          shardCount: 2
      - name: function-logs
        option:
          ttl: 10
          shardCount: 2
`````

@anycodes @whaohan  有什么问题可以一起讨论，如果没有问题大概下周一或者下周二可以出一个版本体验一下
