### ISSUE TITLE
配置文件中 Services 字段 role 参数 policy 重复添加

### ISSUE THREAD

**Issue by whaohan** [devsapp/fc#132]
在[YAML规范说明](https://github.com/devsapp/fc/blob/main/docs/Others/yaml.md#service字段)的 services 字段中，给出了 role 参数的两种配置：

![Role Config](https://i.loli.net/2021/07/23/2G8coAXpW6iVgUx.png)

**当使用结构体来配置 role 时，如果该 service 下有多个 function，会引发报错。**

报错部分配置如下：

```
vars:
  video-demo:
    name: video-demo
    role:
      name: video-demoDefaultRole
      policies:
        - Version: '1'
          Statement:
            - Effect: Allow
              Action:
                - oss:ListObjects
                - oss:GetObject
                - oss:PutObject
                - fc:InvokeFunction
              Resource: '*'

services:
  fc-video-demo-split:
    component: devsapp/fc
    props:
      service: ${vars.video-demo}
      function:
        name: split
        handler: index.handler
  fc-video-demo-transcode:
    component: devsapp/fc
    props:
      service: ${vars.video-demo}
      function:
        name: transcode
        handler: index.handler
```

该服务下 function 部署时， policies 会被重新附加到已有 role 中，从而引起报错：

![Error](https://i.loli.net/2021/07/23/EbDK5cgp3s8zGSr.png)

**Comment by wss-git** [comment]
您的 policies 自定义时格式错误，缺少一个层级
````
policies:
  - FC-post-log-to-qwe123-lllll23123 # 已经存在的策略
  - AliyunContainerRegistryReadOnlyAccess  # 系统策略
  - AliyunContainerRegistryReadOnlyAccess  # 重复的系统策略
  - name: policy-test
    statement: # 策略配置
      - Effect: Deny
        Action:
          - sts:AssumeRole
        Resource: '*'
````
