### ISSUE TITLE
s init 生成  Puppeteer - Front-end Example 不可用

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#140]
![image](https://user-images.githubusercontent.com/10919599/127273578-33cf1982-2a5f-41e8-b3ea-f72d9f3eac7d.png)

![image](https://user-images.githubusercontent.com/10919599/127273540-e040ad09-216b-401a-932c-7771e53f256c.png)

依赖一些 apt  install， 同时最好将这个示例的 runtime 使用  nodejs12

**Comment by rsonghuster** [comment]
或者直接使用开源之夏那个同学做好了， 基于 custom container 的替换掉这个

**Comment by anycodes** [comment]
这个原先就是nodejs的哈：

```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: functionApp       #  项目名称
access: aliyun-release  #  秘钥别名

services:
  function-test: #  服务名称
    component: fc  # 组件名称
    props: #  组件的属性值
      region: cn-hangzhou
      service:
        name: ServerlessToolProject
        description: 欢迎使用ServerlessTool
      function:
        name: serverless_demo_nodejs12
        description: 这是一个Nodejs12的测试案例
        codeUri: ./
        handler: index.handler
        memorySize: 128
        runtime: nodejs12
        timeout: 5
```

这个如果有新的更新，直接release，自动更新的哈，不用手动替换。
