### ISSUE TITLE
自定义 endpoint， system_url 返回错误

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#157]
````
fc-deploy-test:
  region: cn-shenzhen
  service:
    name: fc-deploy-service
  function:
    name: http-trigger-function
    runtime: nodejs10
    handler: index.handler
    memorySize: 128
    timeout: 3
  url:
    system_url: >-
      https://*********.cn-shenzhen.fc.aliyuncs.com/2016-08-15/proxy/fc-deploy-service/http-trigger-function/
  triggers:
    - type: http
      name: httpTrigger
````
