### ISSUE TITLE
链路追踪的权限问题

### ISSUE THREAD

**Issue by Laura-monkey** [devsapp/fc#162]
链路追踪是arms的权限么？不应该是xtrace?
![image](https://user-images.githubusercontent.com/85347842/128135495-4c717d1d-8007-4dd6-9bd9-d08eb3864c17.png)

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/128678210-09ab1ea8-af15-4139-a78b-e86296496bf9.png)
@rsonghuster  麻烦看看着同学看看呢， 接口抛出的错误

yaml 文件
````
edition: 1.0.0 
name: fcDeployApp

services:
  fc-deploy-test: 
    component: devsapp/fc 
    props: 
      region: cn-shenzhen
      service:
        name: unit-deploy-service
        description: 'demo for fc-deploy component'
        internetAccess: true
        tracingConfig: Enable
````

子账号的权限
![image](https://user-images.githubusercontent.com/56686088/128678394-38d5c295-6f45-4fa2-9880-9890d87c9589.png)
