### ISSUE TITLE
s local start 镜像仓库地址 bug

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#199]
在如下 s.yaml 配置下执行 s local start，显示启动成功
<img width="1050" alt="图片" src="https://user-images.githubusercontent.com/626967/129359148-7fef73d6-6743-4b7b-9352-ede1ef945e43.png">

在控制台中访问红框中的 url，显示如下错误：
<img width="1069" alt="图片" src="https://user-images.githubusercontent.com/626967/129359013-38fcb609-ff44-4b09-b4e5-bd663297b213.png">

可见镜像地址被错误的拼上了 registry.cn-beijing.aliyuncs.com 

附 s.yaml 配置内容
```
edition: 1.0.0
name: pytorch-serve
access: default
vars:
  region: cn-hangzhou
services:
  pytorch-serve:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: pytorch-serve
        role: acs:ram::43716:role/FCDefaultRole
        internetAccess: true
      function:
        name: inference
        description: AI inference based on PyTorch serving framework.
        handler: not-used
        timeout: 60
        caPort: 8080
        memorySize: 1536
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-hangzhou.aliyuncs.com/yhr-work/torchserve
      triggers:
        - name: http-trigger-test
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
```
