### ISSUE TITLE
报错 unknown command deploy

### ISSUE THREAD

**Issue by zjxpcyc** [devsapp/fc#395]
之前是一个 fun 项目。我手动修改了一个配置文件。然后直接执行 `s deploy` . 就报错 
```bash
[2021-11-01T19:18:43.886] [ERROR] [S-CLI] -   error: unknown command deploy
```

配置文件 `s.yaml`

```yaml
edition: 1.0.0
name: job-for-serverless
access: default

services:
  http-cron:
    component: devsapp/fc
    props:
      region: cn-shanghai
      service:
        name: http-cron
        internetAccess: true
        description: 'HTTP 定时任务'
      function:
        name: job-for-serverless
        description: ''
        runtime: custom
        codeUri: './code.zip'
        memorySize: 512
        timeout: 60
      triggers:
        - name: go-job-trigger
          type: timer
          config:
            cronExpression: '0 */1 * * * *'
            enable: true
```
