### ISSUE TITLE
关于 nas 操作异常

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#43]
复现步骤：

1. 修改自定义 nas 配置，配置如下，执行 s deploy，没有生效
````
nasConfig:
      userId: 10003
      groupId: 10003
      mountPoints:
        - serverAddr: ***-****.cn-hangzhou.nas.aliyuncs.com
          nasDir: /
          fcDir: /mnt/auto
````
![image](https://user-images.githubusercontent.com/56686088/123614800-3cd00a00-d837-11eb-8402-9493e32038f0.png)

2. 配置 nasConfig: auto，然后执行 s deploy
