### ISSUE TITLE
使用remove的时候，返回结果结构不合理

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#482]
```
triggers:
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
  - httpTrigger
functions:
  - bottle
  - django
  - egg
  - exaapress
  - express
  - expressd
  - flask
  - hapi
  - koa
  - next
  - nuxt
  - pyramid
  - tornado
  - webpy
service: web-framework
```

这里的结构应该是：
```
service: 
  serviceName: web-framework: 
  functions: 
       - functionName: bottle
          triggers:
               - httpTrigger
       - functionName: django
          riggers:
               - httpTrigger
       - functionName: egg
          triggers:
               - httpTrigger
```

**Comment by wss-git** [comment]
这样是不是更合理一点，因为上面那种表现不出来我们到底删除那个资源，比如：s remove function 或者 s remove trigger

````
<project-name>: 
  service: serviceName
  functions: 
       - service: serviceName
          function: functionName1
       - service: serviceName
          function: functionName2
 triggers: 
       - service: serviceName
          function: functionName1
          trigger: triggerName1
       - service: serviceName
          function: functionName1
          trigger: triggerName2
````
