### ISSUE TITLE
s local start 调试代码异常

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#509]
现象 1（异常）:  
1. 执行 npm i，然后执行 s local start auto
2. 访问地址报错
现象 2：
1. 将 s.yaml 的 function name 修改为 http
2. 访问地址，没有异常
现象 3：
1. s init devsapp/start-fc-http-nodejs12 ， 生成同样的 yaml
2.  s local start auto 访问地址，没有异常

![image](https://user-images.githubusercontent.com/56686088/145781377-2d893aeb-c904-4bb3-90d1-680178aa79e4.png)

````yaml
edition: 1.0.0
name: hello-world-app
access: "default-1"

vars: # 全局变量
  region: cn-hangzhou
  service:
    name: hello-world-service
    description: 'hello world by serverless devs'

services:
  helloworld: # 业务名称/模块名称
    component: devsapp/fc
    props: #  组件的属性值
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: http-trigger-nodejs12
        description: 'hello world by serverless devs'
        runtime: nodejs12
        codeUri: ./code
        # ossBucket:
        # ossKey:  # conflict with codeUri
        handler: index.handler
        memorySize: 512
        timeout: 60
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
````

````js
const proxy = require('@webserverless/fc-express')
const express = require('express');
const getRawBody = require('raw-body');

const app = express();
app.all('*', (req, res) => {
  res.send('hello world!');
});

const server = new proxy.Server(app);


module.exports.handler = async (req, res, context) => {
  req.body = await getRawBody(req); // 本行代码一定要放到其他 await 代码之前
  // await init();
  server.httpProxy(req, res, context);
};
````

````package.json
{
  "name": "main",
  "dependencies": {
    "@webserverless/fc-express": "1.0.0",
    "express": "4.17.1"
  }
}

````
