### ISSUE TITLE
s plan看得不是很懂

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#512]
![image](https://user-images.githubusercontent.com/21079031/146176994-eb22e6d1-286c-4836-88a5-77b417af6788.png)

这里面的release => new到底是啥/

到底是release是下面的，还是new是下面的？
```
  description: "Serverless Devs Web Framework Service"
  name: "web-framework"
```

但是下面这种形式就会很清晰：
![image](https://user-images.githubusercontent.com/21079031/146177548-e5c59b33-8790-4afd-8a93-ec853e93236c.png)

所以这一部分要改，容我再想一下，怎么优化处理一下。

**Comment by anycodes** [comment]
把下面的输出：
```
region: cn-beijing


Resources(service) to change (release => new):
  description: "Serverless Devs Web Framework Service" => "Saaaaerverless Devs Web Framework Service"
  name: "web-framework"



Resources(function) to change (release => new):
  caPort: 9000
  description: "Serverless Devs Web Framework Fastapi Function"
- environmentVariables: {"LD_LIBRARY_PATH":"/code/.s/root/usr/local/lib:/code/.s/root/usr/lib:/code/.s/root/usr/lib/x86_64-linux-gnu:/code/.s/root/usr/lib64:/code/.s/root/lib:/code/.s/root/lib/x86_64-linux-gnu:/code/.s/root/python/lib/python2.7/site-packages:/code/.s/root/python/lib/python3.6/site-packages:/code:/code/lib:/usr/local/lib","NODE_PATH":"/code/node_modules:/usr/local/lib/node_modules","PATH":"/code/.s/root/usr/local/bin:/code/.s/root/usr/local/sbin:/code/.s/root/usr/bin:/code/.s/root/usr/sbin:/code/.s/root/sbin:/code/.s/root/bin:/code:/code/node_modules/.bin:/code/.s/python/bin:/code/.s/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin","PYTHONUSERBASE":"/code/.s/python"}
  handler: "index.handler"
  instanceConcurrency: 1
  instanceType: "e1"
  memorySize: 128
  name: "fastapi"
  runtime: "custom"
  timeout: 60



Resources(triggers) to change (release => new):
  config: {
    authType: "anonymous"
    methods: [
    "\u001b[22m\"GET\"\u001b[0m"]
  }
  name: "httpTrigger"
  type: "http"



Resources(domains) to change (release => new):
  domainName: "fastapi.web-framework.1583208943291465.cn-beijing.fc.devsapp.net"
  protocol: "HTTP"
  routeConfig: [
    0: {
      functionName: "fastapi"
    - methods: ["GET"]
      path: "/*"
      serviceName: "web-framework"
    }
  ]
```
转换为这样：
```
region: cn-beijing
service:
  description: [黄色] "Serverless Devs Web Framework Service" => "Saaaaerverless Devs Web Framework Service"
  name: "web-framework"
function:
  caPort: 9000
  description: "Serverless Devs Web Framework Fastapi Function"
  - [红色]environmentVariables: {"LD_LIBRARY_PATH":"/code/.s/root/usr/local/lib:/code/.s/root/usr/lib:/code/.s/root/usr/lib/x86_64-linux-gnu:/code/.s/root/usr/lib64:/code/.s/root/lib:/code/.s/root/lib/x86_64-linux-gnu:/code/.s/root/python/lib/python2.7/site-packages:/code/.s/root/python/lib/python3.6/site-packages:/code:/code/lib:/usr/local/lib","NODE_PATH":"/code/node_modules:/usr/local/lib/node_modules","PATH":"/code/.s/root/usr/local/bin:/code/.s/root/usr/local/sbin:/code/.s/root/usr/bin:/code/.s/root/usr/sbin:/code/.s/root/sbin:/code/.s/root/bin:/code:/code/node_modules/.bin:/code/.s/python/bin:/code/.s/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin","PYTHONUSERBASE":"/code/.s/python"}
  handler: "index.handler"
  instanceConcurrency: 1
  instanceType: "e1"
  memorySize: 128
  name: "fastapi"
  runtime: "custom"
  timeout: 60
triggers:
  config: 
    authType: "anonymous"
    methods:
        - "GET"
  name: "httpTrigger"
  type: "http"
domains:
  domainName: "fastapi.web-framework.1583208943291465.cn-beijing.fc.devsapp.net"
  protocol: "HTTP"
  routeConfig:
      - functionName: "fastapi"
         [红色]- methods: ["GET"]
         path: "/*"
         serviceName: "web-framework"
```
