### ISSUE TITLE
caPort不生效

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#519]
使用fc@dev版本，更新caPort不生效，删除缓存也不行

```yaml
edition: 1.0.0        #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: springboot   #  项目名称
access: "test-2"  #  秘钥别名

services:
  springboot:
    component: devsapp/fc@dev
    actions:
      pre-deploy: # 在deploy之前运行
        - run: mvn package  # 要运行的命令行
          path: ./code # 命令行运行的路径
    props:
      region: cn-beijing
      service:
        name: webframework
        description: This is a FC service for springboot
        logConfig: auto
          #nasConfig: Auto
        #        logConfig: auto
      function:
        name: springboot
        codeUri: ./code
        runtime: custom
        caPort: 8080
        memorySize: 1024
        timeout: 60
      triggers:
          - name: httpTrigger
            type: http
            config:
              authType: anonymous
              methods:
                - GET
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
```

1. s deploy && s info
![image](https://user-images.githubusercontent.com/5763215/146757979-5f208554-5a27-4de5-a388-0a94efad4124.png)

2. s plan
![image](https://user-images.githubusercontent.com/5763215/146758026-b021cbe4-832c-4206-a279-e1f8f127a0df.png)

可以看到无论是s info还是s plan，caPort都是9000，不是本地的8080
