### ISSUE TITLE
密钥选择没有传递，没有都要用户重新选择

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#522]
我的`s.yaml`配置
```
edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: fcDeployApp       #  项目名称
access: default-1  #  秘钥别名

vars:
  component: ${path(../..)}
  # component: devsapp/fc
  region: cn-hangzhou
  service:
    name: demo-wss
    description: demo for fc-deploy component233
    internetAccess: true
    vpcConfig: auto

services:
  t1:
    component: ${vars.component}
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: node-demo
        description: this is a test
        runtime: nodejs10
        codeUri: ./code
        handler: index.handler
        memorySize: 128
        timeout: 60
        instanceConcurrency: 1
        instanceType: e1
        environmentVariables:
          testEnv: true
        customDNS:
          nameServers:
            - 8.8.8.8
            - 114.114.114.114
          searches:
            - default.svc.test.example
            - svc.jqDgWvOo.test.example
          dnsOptions:
            - name: ndots
              value: 6
            - name: edns
              value: 79
        instanceLifecycleConfig:
          preFreeze:
            handler: index.preFreeze
            timeout: 60
          preStop:
            handler: index.preStop
            preStop: 60
        asyncConfiguration:
          # destination:
          #   onSuccess: acs:fc:::services/ServerlessTool.LATEST/functions/serverless_demo_nodejs8_http
          #   onFailure: acs:fc:::services/Puppeteer.LATEST/functions/HtmlToPng
          maxAsyncEventAgeInSeconds: 567
          maxAsyncRetryAttempts: 3
          statefulInvocation: false
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: '/*'
```
我本地并没有`default-1`的密钥，这里我执行`s deploy`命令，需要多次交互式选择密钥
![image](https://user-images.githubusercontent.com/5129967/146963011-6938732f-76b1-4fcd-ae41-04391e55d7e9.png)
