### ISSUE TITLE
fun2s组件转换成s的规范有bug

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#538]
midway生成的组件形式
```
services:
  CustomDomain-midway_auto_domain:
    component: devsapp/fc-domain
    props:
      region: ${vars.region}
      customDomain:
        domainName: Auto
        protocol: HTTP
        routeConfigs: []
```

**Comment by wss-git** [comment]
用户的 yaml 片段如下，routes => Routes 才对。 fun 对大小写很敏感的，这个使用fun 也是报错的
````
midway_auto_domain:
    Type: Aliyun::Serverless::CustomDomain
    Properties:
      DomainName: Auto
      Protocol: HTTP
      RouteConfig:
        routes:
          /deploy:
            serviceName: serviceName
            functionName: functionName
````
