### ISSUE TITLE
关于fc组件service字段问题讨论

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#555]
现在关于service的误解很多，我们能否把service和function的抽出单独的组件出来？
```yaml
services:
  fc-service: 
    component: devsapp/fc-service
    props:
      region: cn-hangzhou
      name: test-service
      internetAccess: true
      logConfig: auto
      nasConfig: auto
      role: ''
      
  fc-function-1:
    component: devsapp/fc-function
    props:
      region: ${vars.region}
      serviceName: ${service.fc-service.output.name} #指定当前工程的service
      handler: index.handler
      instanceConcurrency: 1
      instanceType: e1
      memorySize: 512
      runtime: nodejs12
      timeout: 60
      name: fc-function-1
      codeUri: .
      
  fc-function-2:
    component: devsapp/fc-function
    props:
      region: ${vars.region}
      serviceName: test
      handler: index.handler
      instanceConcurrency: 1
      instanceType: e1
      memorySize: 512
      runtime: nodejs12
      timeout: 60
      name: fc-function-2
      codeUri: .
```
这样的好处是：
1. service不会有歧义
2. 不用每次部署function时再check service
