### ISSUE TITLE
定义多个函数后，执行 s local start auto 出错

### ISSUE THREAD

**Issue by hryang** [devsapp/fc#565]
s.yaml 中定义了3个服务/函数，执行 s local start auto 时，期望 3 个函数在本地启动成功，但报如下错误：
![图片](https://user-images.githubusercontent.com/626967/147847715-5a29854a-0a0b-4071-91de-1b02ad29aa3f.png)

只有一个函数成功（mall-admin/mall-admin），而 mall-portal/mall-portal 和 mall-search/mall-search 都失败了。错误为：[2022-01-01 09:12:37] [ERROR] [FC] - Unsupported subcommand auto for local method, only start and invoke are supported.

s.yaml 的内容如下所示：
```yaml
edition: 1.0.0
name: mall
access: quanxi-hryang
vars:
  region: cn-hangzhou

# Define the Serverless-Devs services. Each service is a FC function.
services:
  mall-admin:
    component: devsapp/fc
    props:
      region: ${vars.region}
      # Define the AlibabaCloud FunctionCompute Service.
      service: 
        name: mall-admin
        internetAccess: true
        # Let the serverless-devs create a shared logstore automatically.
        # All FC services share the same logstore.
        logConfig: auto 
      # Define the AlibabaCloud FunctionCompute Function.
      function: 
        name: mall-admin
        description: The mall project based on SpringBoot+MyBatis. https://github.com/macrozheng/mall
        caPort: 8080
        memorySize: 3072
        handler: not-used
        timeout: 60
        runtime: custom-container
        customContainerConfig:
          image: registry.${vars.region}.aliyuncs.com/quanxi-hryang/mall-admin:1.0-SNAPSHOT
          # Enable the image acceleration.
          accelerationType: Default
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: mall-admin
              functionName: mall-admin
              methods:
                - GET
                - POST
  mall-portal:
    component: devsapp/fc
    props:
      region: ${vars.region}
      # Define the AlibabaCloud FunctionCompute Service.
      service: 
        name: mall-portal
        internetAccess: true
        # Let the serverless-devs create a shared logstore automatically.
        # All FC services share the same logstore.
        logConfig: auto 
      # Define the AlibabaCloud FunctionCompute Function.
      function:
        name: mall-portal
        description: The mall project based on SpringBoot+MyBatis. https://github.com/macrozheng/mall
        caPort: 8085
        memorySize: 3072
        handler: not-used
        timeout: 60
        runtime: custom-container
        customContainerConfig:
          image: registry.${vars.region}.aliyuncs.com/quanxi-hryang/mall-portal:1.0-SNAPSHOT
          # Enable the image acceleration.
          accelerationType: Default
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: mall-portal
              functionName: mall-portal
              methods:
                - GET
                - POST
  mall-search:
    component: devsapp/fc
    props:
      region: ${vars.region}
      # Define the AlibabaCloud FunctionCompute Service.
      service:
        name: mall-search
        internetAccess: true
        # Let the serverless-devs create a shared logstore automatically.
        # All FC services share the same logstore.
        logConfig: auto 
      # Define the AlibabaCloud FunctionCompute Function.
      function:
        name: mall-search
        description: The mall project based on SpringBoot+MyBatis. https://github.com/macrozheng/mall
        caPort: 8081
        memorySize: 3072
        handler: not-used
        timeout: 60
        runtime: custom-container
        customContainerConfig:
          image: registry.${vars.region}.aliyuncs.com/quanxi-hryang/mall-search:1.0-SNAPSHOT
          # Enable the image acceleration.
          accelerationType: Default
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: mall-search
              functionName: mall-search
              methods:
                - GET
                - POST
  
# https://github.com/devsapp/fc

```
