### ISSUE TITLE
关于部署自定义域名的建议

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#57]
如果仅定义一个 customDomains 模块，我们是否可以直接部署呢？而不是不需要将 服务、函数、触发器都填上才可以部署
````
services:
  fc-deploy-test: 
    component: devsapp/fc 
    props:
      region: cn-shenzhen
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: unit-deploy-service
              functionName: event-function
````

**Comment by anycodes** [comment]
我理解，这个下面本身就不需要写serviceName和functionName吧，默认就是当前的

**Comment by wss-git** [comment]
> 我理解，这个下面本身就不需要写serviceName和functionName吧，默认就是当前的

不是的， region、domainName、serviceName 和 functionName 都已经存在，理解自定义域名所有的配置都已经存在了，按理说这个单独的资源应该是可以部署的，但是我们目前不支持 必须要配置 service、function、triggers 这个三个对映资源才可以部署

**Comment by anycodes** [comment]
@git-qfzhang qianfeng确定一下这里，我印象中之前说如果上面有service，function等，domain的可以这样：

```
customDomains:
  - domainName: auto
    protocol: HTTP
    routeConfigs:
      - path: /*
```
