### ISSUE TITLE
s info 未返回自定义域名信息

### ISSUE THREAD

**Issue by lowkeyrd** [devsapp/fc#575]
```yaml
 helloworld-nodejs:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: http-trigger-nodejs12
        description: hello world by serverless devs
        runtime: nodejs12
        codeUri: ./code-js
        handler: index.handler
        memorySize: 128
        timeout: 600
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
```
1. s info 未返回域名：
![image](https://user-images.githubusercontent.com/5763215/148242724-d84e6b9c-854a-4bff-b790-ac39b254ebec.png)
2. s deploy返回了自定义域名
![image](https://user-images.githubusercontent.com/5763215/148242847-2684dab6-1200-469d-abee-0c4790a8f125.png)
