### ISSUE TITLE
java runtime build 问题

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/fc#602]
在 java runtime 的开发过程中， 我们的最佳推荐是用户能使用 s 工具

```bash
$ s init devsapp/start-fc-http-java8
$ cd start-fc-http-java8
$ 在 pom.xml 增加自己的依赖， 然后修改 App.java 的代码
# 如果本地没有安装 openjdk 和 maven， 需要使用 s build --use-docker
$ s build 
$ s deploy 
```

![image](https://user-images.githubusercontent.com/10919599/149895756-a04ace85-e03d-4f9c-8231-8bd0873010ae.png)

s build 之后，s deploy 会自动将上图所示的一起 zip,  然后作为 zip 包创建函数， 这个是没有问题的。

但是，如果用户第一次看到文档， 没有使用 s 工具，他期望的应该是直接可以 mvn package  就可以自动将所有依赖一起打成一个 jar 包；然后使用这个 jar 包创建函数即可， 但是现在的行为， 是不会自动将所有依赖打成一个 jar 包，直接使用， 调用函数的时候， 会出现找不到依赖包中的 class 情况

**Comment by rsonghuster** [comment]
如果这个解决了， 文档同学也比较好写这块， 之前那个java 的文档， 使用idea打包，很多人估计 hello world 都跑步起来

**Comment by hryang** [comment]
我们不能强迫用户一定要使用 s build。需要做到 mvn package 打包就能到直接使用。

**Comment by rsonghuster** [comment]
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>example</groupId>
  <artifactId>ServerlessToolProject</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>ServerlessToolProject</name>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.aliyun.fc.runtime</groupId>
      <artifactId>fc-java-core</artifactId>
      <version>1.3.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
        <executions>
          <execution>
            <id>make-my-jar-with-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <properties>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.test.skip>true</maven.test.skip>
  </properties>
</project>
```

pom.xml  是这样就好了， 相比较我们 s init 出来的  pom.xml， 增加了这个 build 区域， build 约定 mvn package 生成的是无依赖的 jar 包

所以目前在不改变现有的行为下,  模板中的 pom.xml 修改， 同时 s.yaml 改成如下:

```yaml
services:
  helloworld: # 业务名称/模块名称
    component:  fc
    actions: 
      pre-deploy: 
        - run: mvn package
          path: ./ 
    props: #  组件的属性值
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: event-java8
        description: 'hello world by serverless devs'
        runtime: java8
        codeUri: ./target/ServerlessToolProject-1.0-SNAPSHOT-jar-with-dependencies.jar
```
