### ISSUE TITLE
customRuntimeConfig 不生效

### ISSUE THREAD

**Issue by heimanba** [devsapp/fc#624]
输出的 base64信息应该去掉，无法排查

**Comment by heimanba** [comment]
## next.js 的示例
```
edition: 1.0.0
name: serverless-devs-app
access: "default"

vars: # 全局变量
  region: cn-beijing
  service:
    name: serverless-devs-ui
    description: "Serverless Devs Web Framework Service"

services:
  framework: # 业务名称/模块名称
    component: fc
    actions:
      # pre-deploy: # 在deploy之前运行
      #   - run: npm install --production # 要运行的命令行
      #     path: ./code # 命令行运行的路径
      #   - run: npm run build # 要运行的命令行
      #     path: ./code # 命令行运行的路径
      #   - run: rm -rf node_modules/typescript
      #     path: ./code # 命令行运行的路径
    props: # 组件的属性值
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: registry
        description: "Serverless Devs Web Framework Next.js Function"
        codeUri: "./code"
        runtime: custom
        timeout: 60
        caPort: 9000
        customRuntimeConfig:
          command:
            - next
            - start
          args:
            - --port
            - 9000
          # command:
          #   - next
          #   - start
          # args:
          #   - '--port'
          #   - 9000
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: "/*"
```

## 问题1
使用bootstrap是OK 的
```
#!/bin/bash
npx next start --port 9000
```

## 问题2
执行--debug 时候疯狂输出base64等zip信息

## 问题3 
执行--debug的时候失败啦，一直在循环。。。并没有退出
