### ISSUE TITLE
自定义域名这里需要确定一下文档

### ISSUE THREAD

**Issue by anycodes** [devsapp/fc#686]
![image](https://user-images.githubusercontent.com/21079031/159132264-96e13e65-c600-4323-ad01-951e23c7ff8c.png)

貌似这两个参数是有问题？

![image](https://user-images.githubusercontent.com/21079031/159132274-ed19cc6b-b0f3-4aff-b4b6-8ddbc7b4d0f3.png)

![image](https://user-images.githubusercontent.com/21079031/159132282-8341feda-ab32-4c59-9326-87d0547f6574.png)

**Comment by heimanba** [comment]
protocol这里文档取值有问题

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/159646539-1b67eb21-f53d-4a35-b767-4d1fdf53d2fa.png)
文档已修复

**Comment by wss-git** [comment]
https://github.com/devsapp/fc/blob/main/docs/zh/yaml/customDomains.md#%E9%80%9A%E8%BF%87%E9%85%8D%E7%BD%AE-certid-%E8%8E%B7%E5%8F%96%E8%AF%81%E4%B9%A6%E5%86%85%E5%AE%B9

**Comment by wss-git** [comment]
使用方式：
yaml 配置：
````
customDomains:
        - domainName: test.shoushuai.top
          protocol: HTTP,HTTPS
          certId: xxxxxx
          routeConfigs:
            - path: /*
              methods:
                - GET
````

certId 获取方式
![image](https://user-images.githubusercontent.com/56686088/159652035-d6b55518-68dc-4adc-b409-18f486aff167.png)
