### ISSUE TITLE
fun2s 不能正确的转换模板文件

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/fc#732]
使用 fc 0.1.49 版组件对已有的 funcraft template.yaml 文件进行迁移时无法正确的转换成 @serverless-devs/s 的 s.yaml 文件.

转换后的 s.yaml 总是只包含以下内容:

```yaml
edition: 1.0.0
name: transform_fun
access: default
vars:
  region: cn-shenzhen
services: {}
```

复现步骤与示例工程: https://github.com/DevDengChao/aliyun-fc-issues/tree/master/serverless-devs/fun2s-not-works-when-using-fc-0.1.49
