### ISSUE TITLE
yaml中一个service中配置custom domain，s deploy后会更改custom domain针对其他service的配置。

### ISSUE THREAD

**Issue by crazylnx** [devsapp/fc#733]
**对于custom domain: wordpress.web-framework.1816647648916833.cn-hangzhou.fc.devsapp.net
控制台配置中path指向不同的service，如下图所示：**
![image](https://user-images.githubusercontent.com/15911068/165751728-247eb8dd-22cf-41d9-8cf3-3125f62487b6.png)

**一个新的ymal，custom domain中配置了routeConfigs如下：**
``` ymal
services:
  dummy-function:
    component: devsapp/fc
    props:
      region: cn-hangzhou
      service:
        name: test-new
        logConfig: auto
        nasConfig: auto
      function:
        handler: index.handler
        instanceType: e1
        memorySize: 1024
        runtime: nodejs12
        timeout: 60
        name: dummy-function
        codeUri: ./code
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: wordpress.web-framework.1816647648916833.cn-hangzhou.fc.devsapp.net
          protocol: HTTP
          routeConfigs:
            - path: '/index'
```
**此时执行s deploy 成功后，再次检查控制台，发现path为/cat的配置被删除了。如下图**
![image](https://user-images.githubusercontent.com/15911068/165752272-8493f8fe-5a14-45bc-8e3c-d8ea64fda733.png)

**我认为对于一个custom domain 是可以服务于多个service的，部署一个服务的custom domain应该是patch的过程，当前的部署customdomain行为不正确。**

**Comment by anycodes** [comment]
1. devsapp的域名仅供测试使用，不支持更多其他的操作；
2. 这个删掉了其他path的事情 @wss-git

**Comment by wss-git** [comment]
这一项是配置，并不是资源，如果配置不全会被替换掉，可以配置配置下面这种，[参考文档](https://docs.serverless-devs.com/fc/yaml/customDomains#routeconfigs)  routeconfigs 是个数组哈

````
customDomains:
        - domainName: wordpress.web-framework.1816647648916833.cn-hangzhou.fc.devsapp.net
          protocol: HTTP
          routeConfigs:
            - path: '/index'
              serviceName: test-new
              functionName: dummy-function
            - path: '/cat'
              serviceName: dummy-service
              functionName: dummy-function
````

**Comment by crazylnx** [comment]
如果custom domain是一个配置，用户使用会冗余，而且会有错误配置的风险，如下所示：
第一个yaml：
``` yml
edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: demo-app #  项目名称
access: 'mac0307' #  秘钥别名

services:
  dummy-function-1:
    component: devsapp/fc
    props:
      region: cn-hangzhou
      service:
        name: test-new-1
        logConfig: auto
        nasConfig: auto
      function:
        handler: index.handler
        instanceType: e1
        memorySize: 1024
        runtime: nodejs12
        timeout: 60
        name: dummy-function-1
        codeUri: ./code
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: wordpress.web-framework.1816647648916833.cn-hangzhou.fc.devsapp.net
          protocol: HTTP
          routeConfigs:
            - path: '/index'
              serviceName: test-new-1
              functionName: dummy-function-1
            - path: '/cat' 
              serviceName: test-new-2
              functionName: dummy-function-2
```
第二个yaml
```yml
edition: 1.0.0 #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: demo-app #  项目名称
access: 'mac0307' #  秘钥别名
services:
  dummy-function-2:
    component: devsapp/fc
    props:
      region: cn-hangzhou
      service:
        name: test-new-2
        logConfig: auto
        nasConfig: auto
      function:
        handler: index.handler
        instanceType: e1
        memorySize: 1024
        runtime: nodejs12
        timeout: 60
        name: dummy-function-2
        codeUri: ./code
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
      customDomains:
        - domainName: wordpress.web-framework.1816647648916833.cn-hangzhou.fc.devsapp.net
          protocol: HTTP
          routeConfigs:
            - path: '/index'
              serviceName: test-new-1
              functionName: dummy-function-1
            - path: '/cat'
              serviceName: test-new-2
              functionName: dummy-function-2
```
1. 用户在第一个yaml中custom domain配置里，必须带上第二个yaml的相关配置。同理第二个yaml也要带上第一个yaml的配置。这是冗余的。
2. 任何一个yaml没有带全custom domain的配置，就会造成某个应用/函数不可用。

建议将customDomain 配置改为只针对当前yaml内service下function的配置。如果当前custom domain中存在该yaml内service下function的path，则替换，如果不存在，则补充。
