### ISSUE TITLE
s info trigger 时，需要将最新的 triggerConfig 同步更新至 info 组件中

### ISSUE THREAD

**Issue by git-qfzhang** [devsapp/fc#806]
使用 s 工具对 trigger 进行 info 时，发现新增的字段无法返回给用户，这是因为 info 会限制返回的触发器参数，当触发器参数有更新时，需要同步更新 s 工具的 info 组件；
目前更新的触发器参数：

- eventbridge triggerConfig
- sls triggerConfig

**Comment by wss-git** [comment]
sls 测试 yaml

````yaml
# 深圳地区
triggers:
        - name: log2    
          type: log
          config:      
            sourceConfig:        
              logstore: test2
              startTime: 1660060680  # Unix 时间戳，单位为秒
            jobConfig:        
              maxRetryTime: 3        
              triggerInterval: 60      
            functionParameter: {}      
            logConfig:        
              project: uid-cn-shenzhen-logproject
              logstore: fc-service-fc-test-logstore      
            enable: false
````
