### ISSUE TITLE
domain 配置 qualifier 需要是 string，否则就会异常

### ISSUE THREAD

**Issue by wss-git** [devsapp/fc#876]
```
test:
    component: devsapp/fc
    props:
      region: cn-shanghai
      customDomains:
        - domainName: frontend.serverless-cd-wss.xxxx.ap-southeast-1.fc.devsapp.net
          protocol: HTTP
          routeConfigs:
            - path: /*
              serviceName: serverless-cd-wss
              functionName: ui
              qualifier: 1 # need to '1'
```
![image](https://user-images.githubusercontent.com/56686088/201817114-16e45fdd-d2d9-4bb1-a94e-612113266508.png)
